version: 2

models:
  - name: stg_greenery__addresses
    description: Location (delivery) information associated with greenery's users (GDPR)

  - name: stg_greenery__events
    description: Greenery's users site sessions and events
  
  - name: stg_greenery__orders
    description: Greenery's orders, deliveries and shipping
    columns:
      - name: order_id
        tests:
        - not_null
        - unique

  - name: stg_greenery__order_items
    description: Items per order (including quantity) 
  
  - name: stg_greenery__products
    description: Greenery's products and inventory

  - name: stg_greenery__promos
    description: Greenery's past and current promotions
  
  - name: stg_greenery__users
    description: Demographic information and contact details for greenery's users (GDPR)
    columns:
      - name: user_id
        tests:
        - not_null
        - unique

        